framework:
    messenger:
        failure_transport: failed

        transports:
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                retry_strategy:
                    max_retries: 3
                    delay: 1000
                    multiplier: 2
                    max_delay: 10000
            failed: 'doctrine://default?queue_name=failed'
            sync: 'sync://'

        routing:
            'App\Domain\Event\PaymentCapturedEvent': async

when@test:
    framework:
        messenger:
            transports:
                async: 'in-memory://'
